cmake_minimum_required(VERSION 3.16)
project(DevToolsManager VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

# Detecta Qt6 e Widgets/Core
find_package(Qt6 REQUIRED COMPONENTS Core Widgets Gui)

# Inclui arquivos da pasta src/scr e include
file(GLOB_RECURSE SOURCES
    scr/*.cpp
)
file(GLOB_RECURSE HEADERS
    include/*.h
)

# Executável final
add_executable(${PROJECT_NAME}
    ${SOURCES}
    ${HEADERS}
)

target_include_directories(${PROJECT_NAME} PRIVATE include scr)

target_link_libraries(${PROJECT_NAME}
    PRIVATE Qt6::Core Qt6::Gui Qt6::Widgets
)


